# Generated by Django 3.1.1 on 2020-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_auto_20200929_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
